### ISSUE TITLE
Publish workflow broken and disabled?

### ISSUE THREAD

**Issue by cpu** [addr-rs/psl#4] opened 2023-08-13 14:38 UTC
Hi there,

I notice the ["Publish" workflow](https://github.com/addr-rs/psl/actions) seems to have been broken for some time (and seems to have been disabled since ~July 21st). Is this on your radar?

The reported error is:
```
   Installed package `cargo-release v0.24.8` (executable `cargo-release`)
error: object not found - no match for id (d339930e459c6c6e02ef9bbf4ab44bbae30ef627); class=Odb (9)
Error: Process completed with exit code 101.
```

This error is fairly mysterious and I haven't found any conclusive fixes in my googling. It may be tricky for a non-maintainer to diagnose since the failure looks to be happening at the last stage, running:
`cargo release patch --execute --no-confirm --push-remote upstream`.

**Comment by serega** [comment] 2023-11-14 09:57
This has been [reported](https://github.com/addr-rs/psl/issues/3). The issue is marked as completed, but still not working

**Comment by rushmorem** [comment] 2023-11-16 21:55
Fixed now. Sorry there were some issues with `cargo release`. Switched to `release-plz` now.

**Closed as completed by rushmorem** 2023-11-16 21:55 UTC

**Comment by cpu** [comment] 2023-11-16 22:04
Thanks!

**Comment by rushmorem** [comment] 2023-11-16 22:05
My pleasure!
